# Generated by Django 3.0.4 on 2020-03-13 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.Question')),
                ('answer_order', models.CharField(blank=True, choices=[('none', 'Оруулсан дарааллаар'), ('random', 'Санамсаргүй')], help_text='Шалгалт бүр дээр даалгаврын хариултыг с', max_length=30, null=True, verbose_name='Хариултын эрэмбэ')),
            ],
            options={
                'verbose_name': 'Даалгавар',
                'verbose_name_plural': 'Даалгаврууд',
            },
            bases=('quiz.question',),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, default='', help_text='Зохимжит бүх хариултыг оруулна уу. Хэдэн ч хариулттай байж болно.', max_length=1000, verbose_name='Хариулт')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='uploads/problem/pic/%Y/%m/answer', verbose_name='Зураг')),
                ('correct', models.BooleanField(default=False, help_text='Зөвхөн ганцхан хариултыг зөв гэж бөлгөнө үү', verbose_name='Зөв хариулт эсэх')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcq.MCQQuestion', verbose_name='Даалгавар')),
            ],
            options={
                'verbose_name': 'Хариулт',
                'verbose_name_plural': 'Хариултууд',
            },
        ),
    ]
