# Generated by Django 3.0.4 on 2020-03-13 10:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Ай')),
            ],
            options={
                'verbose_name': 'Ай',
                'verbose_name_plural': 'Айнууд',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Түвшин')),
            ],
            options={
                'verbose_name': 'Түвшин',
                'verbose_name_plural': 'Түвшингүүд',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Шалгалтыг төлөөлөх 60 тэмдэгтэд багтсан товч нэршил оруулна уу. Заавал бөглөнө.', max_length=60, verbose_name='Гарчиг')),
                ('description', models.TextField(blank=True, help_text='Шаардлагатай бол шалгалтын зорилгыг тодорхойлж бичнэ үү.', verbose_name='Зорилго')),
                ('url', models.SlugField(help_text='Цаашид уг шалгалтад энэ линк үгээр хандах учраас шалгалтыг төлөөлөх товч латин үг оруулна уу', max_length=60, verbose_name='Шалгалтын линк')),
                ('random_order', models.BooleanField(default=False, help_text='Хэрэглэгч бүрт шалгалтын даалгаврын дарааллыг санамсаргүйгээ өгөх эсэхийг тодорхойлно.', verbose_name='Даалгаврыг санамсаргүйгээр өгөх')),
                ('max_questions', models.PositiveIntegerField(blank=True, help_text='Хамгийн ихдээ уг шалгалт хэдэн даалгавартай байхыг тодорхойлно.', null=True, verbose_name='Даалгаврын тоо')),
                ('answers_at_end', models.BooleanField(default=False, help_text='Энэ тохиргоо даалгавар бөглөөд шууд зөв буруугаа мэдэх эсвэл шалгалтын сүүлд мэдэх эсэхийг тохируулна.', verbose_name='Шалгалтын төгсгөлд даалгавруудын анализийг харах')),
                ('exam_paper', models.BooleanField(default=False, help_text='Шалгалт гэж тодорхойлсон тохиолдолд хэрэглэгчийн бүх явцийг бүртгэнэ.', verbose_name='Шалгалтын дэвтэр эсэх')),
                ('single_attempt', models.BooleanField(default=False, help_text='Хэрэглэгч бүр ганцхан удаа өгнө. Энэ тохиолдолд автоматаар ШАЛГАЛТЫН ДЭВТЭР гэж бүртгэнэ.', verbose_name='Ганцхан оролдлоготой эсэх')),
                ('pass_mark', models.SmallIntegerField(blank=True, default=0, help_text='Хамгийн ихдээ 100 оноо авна. Анхдагч утга нь 0 байгаа.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Нийт авах оноо')),
                ('success_text', models.TextField(blank=True, help_text='Хэрэв хэрэглэгч шалгалтыг амжилттай дуусгавал хэлэх үг бичнэ.', verbose_name='Амжилттай дуусахад гарах үг')),
                ('fail_text', models.TextField(blank=True, help_text='Хэрэв хэрэглэгч шалгалтыг амжилтгүй дуусгавал хэлэх үг бичнэ.', verbose_name='Амжилтгүй дуусахад гарах үг')),
                ('draft', models.BooleanField(blank=True, default=False, help_text='Туршилт тохиолдолд хэрэглэгчдэд харагдахгүй.', verbose_name='Туршилт эсэх')),
            ],
            options={
                'verbose_name': 'Шалгалт',
                'verbose_name_plural': 'Шалгалтууд',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sitting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Даалгаврын дараалал')),
                ('question_list', models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Даалгаврын жагсаалт')),
                ('incorrect_questions', models.CharField(blank=True, max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Буруу даалгавар')),
                ('current_score', models.IntegerField(verbose_name='Одоогийн оноо')),
                ('complete', models.BooleanField(default=False, verbose_name='Дууссан эсэх')),
                ('user_answers', models.TextField(blank=True, default='{}', verbose_name='Хэрэглэгчийн хариулт')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Шалгалт эхлэсэн хугацаа')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Шалгалт дууссан хугацаа')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz', verbose_name='Шалгалт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгч')),
            ],
            options={
                'ordering': ['user_id'],
                'permissions': (('view_sittings', 'Can see completed exams.'),),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(blank=True, default=0, verbose_name='Оноо')),
                ('figure', models.ImageField(blank=True, null=True, upload_to='uploads/problem/pic/%Y/%m/content', verbose_name='Зураг')),
                ('content', models.TextField(help_text='Даалгаврыг ЛаТеКС кодоор оруулна уу?', verbose_name='Даалгавар')),
                ('explanation', models.CharField(blank=True, help_text='Нэг ижилхэн төрлийн даалгаврууд олон болоход дараа нь хайхад хэрэг болохууц нэршил оруулна уу.', max_length=300, verbose_name='Тайлбар')),
                ('video', models.URLField(blank=True, help_text='Агуулгын төрөл зөвхөн видео тохиолдолд YOUTUBE-ийн линк оруулж ажиглана. Бусад тохиолдолд хоосон байна.', verbose_name='Видео хичээлийн линк')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Нийтлэгч')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Category', verbose_name='Ай')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Level', verbose_name='Түвшин')),
                ('quiz', models.ManyToManyField(blank=True, help_text='Сонгохгүй байх болно. Сонгосон тохиолдолд шууд шалгалт руу орно.', to='quiz.Quiz', verbose_name='Шалгалт')),
            ],
            options={
                'verbose_name': 'Даалгавар',
                'verbose_name_plural': 'Даалгаврууд',
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Оноо')),
                ('correct_answer', models.CharField(max_length=10, verbose_name='Зөв хариулт')),
                ('wrong_answer', models.CharField(max_length=10, verbose_name='Буруу хариулт')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Хэрэглэгчийн явц',
                'verbose_name_plural': 'Хэрэглэгчийн явц',
            },
        ),
    ]
