# Generated by Django 3.0.8 on 2020-08-15 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitting',
            options={'ordering': ['-end'], 'permissions': (('view_sittings', 'Can see completed exams.'),)},
        ),
    ]
