# Generated by Django 3.0.4 on 2020-03-13 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=256, null=True, verbose_name='Холбоо барих дугаар')),
                ('gender', models.CharField(blank=True, choices=[('m', 'Эрэгтэй'), ('f', 'Эмэгтэй')], max_length=1, null=True, verbose_name='Хүйс')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics/')),
                ('add_info', models.CharField(blank=True, help_text='Сургууль, анги гэх мэт нэмэлт хэрэг болж магадгүй мэдээлэл оруулах', max_length=300, null=True, verbose_name='Нэмэлт мэдээлэл')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгчийн нэр')),
            ],
            options={
                'verbose_name': 'Хэрэглэгч нэмэх болон бүртгэх',
                'verbose_name_plural': 'Хэрэглэгч нэмэх болон бүртгэх',
            },
        ),
    ]
