# Generated by Django 3.0.4 on 2020-04-23 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_user_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='tuslamj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_group', models.CharField(choices=[('images', 'Зураг'), ('video', 'Видео')], max_length=20, verbose_name='Агуулгын төрөл')),
                ('help_name', models.CharField(help_text='Зураг дээр курсор хүрэхэд дээд талд гарч ирэх нэр', max_length=200, verbose_name='Агуулгын нэр')),
                ('help_title', models.CharField(help_text='Зураг дээр курсор хүрэхэд доод талд гарч ирнэ. Энд богинохон хэмжээний тест оруулах', max_length=200, verbose_name='Агуулгын тухай ойлголт')),
                ('help_image', models.ImageField(help_text='Зөвхөн нүүр хэсэгт харагдах агуулгыг бүрэн төлөөлөхөөц тодорхой ойлгомжтой зураг оруулах', upload_to='help/images/', verbose_name='Зураг')),
                ('help_content', models.FileField(blank=True, help_text='Цааш дарж ороход харагдах дэлгэрэнгүй бодлого эсвэл онолын материалыг зураг хэлбэрээр оруулах', upload_to='help/videos/', verbose_name='Үндсэн файл')),
                ('help_video', models.URLField(blank=True, help_text='Агуулгын төрөл зөвхөн видео тохиолдолд YOUTUBE-ийн линк оруулж ажиглана. Бусад тохиолдолд хоосон байна.', verbose_name='Видео хичээлийн линк')),
            ],
            options={
                'verbose_name': 'Заавар, зөвлөмж',
                'verbose_name_plural': 'Заавар, зөвлөмж',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='teacher_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_teacher', models.BooleanField(default=False, help_text='Сорилго боловсролын цогц системд багшийн эрхээр орж, сурагчдынхаа мэдээллийг үзэх эрхтэй болгох', verbose_name='Багш эсэх')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгчийн нэр')),
            ],
            options={
                'verbose_name': 'Багшлах эрх',
                'verbose_name_plural': 'Багшлах эрх',
            },
        ),
        migrations.CreateModel(
            name='lesson_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_videos', models.BooleanField(default=False, help_text='Уг хэрэглэгч алдсан бодлогынхоо видео бодолтыг үзэх эрхтэй бол заавал сонгоно уу.', verbose_name='Тестийн бодолт үзэх эсэх')),
                ('video_lesson', models.BooleanField(default=False, help_text='Уг хэрэглэгч цуврал хичээлүүдийг үзэх эрхтэй бол заавал сонгоно уу.', verbose_name='Хичээл үзэх эрхтэй эсэх')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгчийн нэр')),
            ],
            options={
                'verbose_name': 'Хэрэглэгчийн нэмэлт эрх',
                'verbose_name_plural': 'Хэрэглэгчийн нэмэлт эрх',
            },
        ),
    ]
